### ISSUE TITLE
Add more test files

### ISSUE THREAD

**Issue by cbrnr** [xdf-modules/example-files#2]
I have a bunch of XDF files that I've used to fix bugs in the reader. Currently, I use these files to perform CI on my local machine, but it would be convenient to have these available online. I thought about dumping them here, but they're 1.6GB and git is not ideal for hosting such large binary files.

I see two options:

1. Go ahead and dump these files here. It does work, and downloading the complete repo is reasonably fast when using the .tar.gz release from GitHub (cloning will be painfully slow though). We're doing this with https://github.com/mne-tools/mne-testing-data.
2. Use Git LFS, with the caveat that everyone needs to install the LFS extension on their local machines.

**Comment by Garfield100** [comment]
Hello,
it's been almost 3 years without a response from the xdf team.
Would you be willing to share these files some other way? I would really appreciate having a suite of testing files for my reader.
Thanks :)

**Comment by cbrnr** [comment]
Sure, I'm willing to share my files, which are mostly open data sets anyway. For those data sets that are not available anywhere else, I have permission to share them from the original creators. The only question is where to share them. I don't want to use my private Cloud space (Google Drive, OneDrive, etc.) for this purpose. GitHub would work, but is not the best (fastest) solution for large binary data files. Maybe OSF is another option, but let me know if I'm missing some dedicated service for sharing large data sets.

**Comment by cboulay** [comment]
Zenodo hosts data.

You could also take a look [at what python-neo does](https://github.com/NeuralEnsemble/python-neo/blob/master/neo/test/rawiotest/common_rawio_test.py#L67-L69) which seems to use Datalad to download from https://gin.g-node.org/NeuralEnsemble/ephy_testing_data.

**Comment by Garfield100** [comment]
Zenodo seems like a perfect fit for this kind of data. Would you be willing to upload it there @cbrnr?

**Comment by cbrnr** [comment]
If we wanted to run integration tests with all data sets, which hosting option would be the best? I mean, if we test _all_ files, each job will have to download the entire 1.6+GB of data every time, which doesn't seem very efficient. So I guess if we add tests, we'll just test on smaller files, right?

Other than that, I don't think it doesn't matter that much if we host on OSF, GIN, or Zenodo. They all provide HTTPS download URLs, so a simple download request should be sufficient without any additional dependencies (like Datalad). I think I'm going to go for OSF.io, I'll post the link to the repo here once it's available.

**Comment by cbrnr** [comment]
Here you go: https://osf.io/uc7wn/

**Comment by Garfield100** [comment]
If you wanted to use integration tests you could use Github's [cache](https://github.com/actions/cache) action to avoid redownloading everything.
Thanks for the upload :)

I know the issue is closed but it might be worth it to at least add the link to the readme or something @cboulay
